// Auto-generated Google Business Profile Local SEO Location Configuration
export const gbpLocation = {
  storeName: "St Clair Cannabis",
  domain: "stclaircannabis.com",
  city: "Toronto",
  province: "ON",
  country: "CA",
  slug: "weed-dispensary-toronto",
  address: "875 St Clair Ave W, Toronto, ON M6C 1C4",
  streetAddress: "875 St Clair Ave W",
  postalCode: "M6C 1C4",
  phone: "(437) 595-3295",
  phoneIntl: "+14375953295",
  neighborhood: "St. Clair / Toronto",
  nearbyAreas: ["St. Clair Avenue", "Wychwood", "Corso Italia", "Oakwood Village", "Hillcrest", "Casa Loma area", "TTC", "Midtown West"],
  products: [
    "Flower",
    "Pre-rolls",
    "Edibles",
    "THC vapes",
    "Concentrates",
    "Shatter",
    "CBD oils",
    "Accessories"
  ],
  menuUrl: "/",
  directionsUrl: "https://www.google.com/maps/search/?api=1&query=875%20St%20Clair%20Ave%20W%2C%20Toronto%2C%20ON%20M6C%201C4",
  mapEmbedUrl: "https://maps.google.com/maps?q=St%20Clair%20Cannabis%20875%20St%20Clair%20Ave%20W%2C%20Toronto%2C%20ON%20M6C%201C4&t=&z=15&ie=UTF8&iwloc=&output=embed",
  latitude: "43.6799300",
  longitude: "-79.4332500",
  hours: ["Open 24 Hours"],
  seoTitle: "St Clair Cannabis | Weed Dispensary in Toronto",
  metaDescription: "St Clair Cannabis is a local weed dispensary in Toronto offering flower, pre-rolls, edibles, vapes, concentrates, CBD, and service for adults 19+.",
  localLandmarks: ["St. Clair Avenue", "Wychwood", "Corso Italia"],
  introVariant: "St Clair Cannabis is your welcoming neighborhood weed dispensary in Toronto, located at 875 St Clair Ave W near St. Clair / Toronto. We carry a massive selection of weed, cannabis flower, pre-rolls, edibles, THC vapes, concentrates, and smoking accessories for adults 19+. Conveniently located near Wychwood, our cannabis store and weed shop is designed to make finding the perfect strain easy and accessible.",
  neighborhoodDescription: "Located in the vibrant St. Clair / Toronto district, our cannabis store fits right into this active and historic community, surrounded by local retail shops and convenient transit links.",
  parkingNote: "Street parking is available along St. Clair Avenue West",
  transitNote: "Accessible via the 512 St. Clair streetcar and local TTC transit routes.",
  sectionTitle: "Serving Customers Near St. Clair Avenue in Toronto"
};
